name: weather-code-training-pipeline-action
run-name: ${{ github.actor }} is running the training pipeline 
on:
  workflow_dispatch:
  schedule:
    - cron: '00 02 * * *'
jobs:
  feature-pipeline-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute Python pipeline from bash script
        env: 
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: ./scripts/run-training-pipeline.sh
